# -*- coding: utf-8 -*-
##############################################################################
#   
#    Copyright (C) 2017 Navybits (<http://www.navybits.com>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
from odoo import fields, models, api, exceptions, _

class beneficiary(models.Model):
    _name = 'test4.beneficiary'

    ##### BEGIN ADDRESS DETAILS #####
    region = fields.Char(string=_(u"Region"))
    street = fields.Char(string=_(u"Street"))
    near = fields.Char(string=_(u"Near"))
    beside = fields.Char(string=_(u"Beside"))
    above = fields.Char(string=_(u"Above"))
    facing = fields.Char(string=_(u"Facing"))
    building = fields.Char(string=_(u"Building"))
    floor = fields.Char(string=_(u"Floor #"))
    ##### END ADDRESS DETAILS #####

    ##### BEGIN PERSONAL DETAILS #####
    name = fields.Char(string=_(u"Name"))
    phone = fields.Char(string=_("Phone"))
    mobile = fields.Char(string=_("Mobile"))
    serial_number = fields.Char(string=_(u"Serial Number")) # THIS SHOULD BE AUTOGENERATED
    gender = fields.Selection(string=_(u"Gender"), 
        selection=[('male',_(u'male')),('female',_(u'female'))],readonly=False)
    is_responsible = fields.Boolean(String =_(u"is responsible"),default=False)
    notes = fields.Text(String=_(u"Additional notes"))

    responsible_id = fields.Many2one('test4.beneficiary',string=_(u"Responsible"),domain=[('is_responsible','=',True)])
    child_ids = fields.One2many('test4.beneficiary','responsible_id',string=_(u"Children of the responsible"))
    ##### END PERSONAL DETAILS #####

    ##### BEGIN SURVEY DETAILS #####
    main_survey_id = fields.Many2one('test4.survey',string=_(u"Surveys"))
    ##### END SURVEY DETAILS #####

    ##### BEGIN SPONSOR DETAILS #####
    sponsor_ids = fields.Many2many('test4.sponsor',string=_(u"Sponsors"))
    ##### END SPONSOR DETAILS #####

    ##### BEGIN PARTNER DETAILS #####
    partner_id = fields.Many2one('res.partner',string=_(u"Partner related"))
    ##### END PARTNER DETAILS #####
    